config/routes.rb
Blog::Application.routes.draw do
  resources :lesson_learneds

  resources :lessons_learned_search

  get "home/index"

  root :to => 'home#index'

end

app/models/lesson_learned.rb
class LessonLearned < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/lesson_learneds_controller.rb
class LessonLearnedsController < ApplicationController

  def initialize
      @rsolr = RSolr.connect :url => 'http://localhost:8983/solr/collection1'
  end

  # GET /lesson_learneds
  # GET /lesson_learneds.json
  def index
    @lesson_learneds = LessonLearned.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lesson_learneds }
    end
  end

  # GET /lesson_learneds/1
  # GET /lesson_learneds/1.json
  def show
    @lesson_learned = LessonLearned.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lesson_learned }
    end
  end

  # GET /lesson_learneds/new
  # GET /lesson_learneds/new.json
  def new
    @lesson_learned = LessonLearned.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lesson_learned }
    end
  end

  # GET /lesson_learneds/1/edit
  def edit
    @lesson_learned = LessonLearned.find(params[:id])
  end

  # POST /lesson_learneds
  # POST /lesson_learneds.json
  def create
    @lesson_learned = LessonLearned.new(params[:lesson_learned])

    respond_to do |format|
      if @lesson_learned.save

        # Now index it in Solr
        @rsolr.add(:id=>@lesson_learned.id,
                   :lesson_date=>@lesson_learned.lessonDate.to_s + 'T00:00:00Z',
                   :project_reference=>@lesson_learned.projectReference,
                   :project_engineer=>@lesson_learned.projectEngineer,
                   :project_architect=>@lesson_learned.projectArchitect,
                   :project_owner=>@lesson_learned.projectOwner,
                   :division=>@lesson_learned.division,
                   :text=>@lesson_learned.input)
        @rsolr.commit

        format.html { redirect_to @lesson_learned, notice: 'Lesson learned was successfully created.' }
        format.json { render json: @lesson_learned, status: :created, location: @lesson_learned }
      else
        format.html { render action: "new" }
        format.json { render json: @lesson_learned.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lesson_learneds/1
  # PUT /lesson_learneds/1.json
  def update
    @lesson_learned = LessonLearned.find(params[:id])

    respond_to do |format|
      if @lesson_learned.update_attributes(params[:lesson_learned])
        # Now index it in Solr
        @rsolr.add(:id=>@lesson_learned.id,
                   :lesson_date=>@lesson_learned.lessonDate.to_s + 'T00:00:00Z',
                   :project_reference=>@lesson_learned.projectReference,
                   :project_engineer=>@lesson_learned.projectEngineer,
                   :project_architect=>@lesson_learned.projectArchitect,
                   :project_owner=>@lesson_learned.projectOwner,
                   :division=>@lesson_learned.division,
                   :text=>@lesson_learned.input)
        @rsolr.commit

        format.html { redirect_to @lesson_learned, notice: 'Lesson learned was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @lesson_learned.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lesson_learneds/1
  # DELETE /lesson_learneds/1.json
  def destroy
    @lesson_learned = LessonLearned.find(params[:id])
    @lesson_learned.destroy

    # Now remove it from Solr
    @rsolr.delete_by_id(@lesson_learned.id)
    @rsolr.commit

    respond_to do |format|
      format.html { redirect_to lesson_learneds_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/lessons_learned_search_controller.rb
class LessonsLearnedSearchController < ApplicationController
  # GET /lessons_learned_search
  # GET /lessons_learned_search.json
  def index
    rsolr = RSolr.connect :url => 'http://localhost:8983/solr/collection1'
    @lessons_learned_search = rsolr.select(:params => { :q=>params[:search], :hl=>true, :"hl.simple.pre"=>"<b>", :"hl.simple.post"=>"</b>" })

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lessons_learned_search }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lesson_learneds_helper.rb
module LessonLearnedsHelper
end

app/helpers/lessons_learned_search_helper.rb
module LessonsLearnedSearchHelper
end

app/views/home/index.html.erb
<h1>Welcome to the wonderful world of learning!</h1>
<form action="/lessons_learned_search">
    <input name="search"/><button type="submit">Submit</button>
</form><%= link_to "Create a new Lesson Learned", new_lesson_learned_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Lessons Learned</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/lesson_learneds/_form.html.erb
<%= form_for(@lesson_learned) do |f| %>
  <% if @lesson_learned.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson_learned.errors.count, "error") %> prohibited this lesson_learned from being saved:</h2>

      <ul>
      <% @lesson_learned.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Lesson Date<br />
    <%= f.date_select :lessonDate %>
  </div>
  <div class="field">
    Project Reference<br />
    <%= f.text_field :projectReference %>
  </div>
  <div class="field">
    Project Engineer<br />
    <%= f.text_field :projectEngineer %>
  </div>
  <div class="field">
    Project Architect<br />
    <%= f.text_field :projectArchitect %>
  </div>
  <div class="field">
    Project Owner<br />
    <%= f.text_field :projectOwner %>
  </div>
  <div class="field">
    Division<br />
    <%= f.text_field :division %>
  </div>
  <div class="field">
    Lesson Learned<br />
    <%= f.text_area :input %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lesson_learneds/edit.html.erb
<h1>Editing lesson_learned</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson_learned %> |
<%= link_to 'Back', lesson_learneds_path %> |
<%= link_to 'Home', root_path %>

app/views/lesson_learneds/index.html.erb
<h1>Listing lesson_learneds</h1>

<table>
  <tr>
    <th>Lesson Date</th>
    <th>Project Reference</th>
    <th>Project Engineer</th>
    <th>Project Architect</th>
    <th>Project Owner</th>
    <th>Division</th>
    <th>Input</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lesson_learneds.each do |lesson_learned| %>
  <tr>
    <td><%= lesson_learned.lessonDate %></td>
    <td><%= lesson_learned.projectReference %></td>
    <td><%= lesson_learned.projectEngineer %></td>
    <td><%= lesson_learned.projectArchitect %></td>
    <td><%= lesson_learned.projectOwner %></td>
    <td><%= lesson_learned.division %></td>
    <td><%= lesson_learned.input %></td>
    <td><%= link_to 'Show', lesson_learned %></td>
    <td><%= link_to 'Edit', edit_lesson_learned_path(lesson_learned) %></td>
    <td><%= link_to 'Destroy', lesson_learned, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lesson learned', new_lesson_learned_path %> |
<%= link_to 'Home', root_path %>

app/views/lesson_learneds/new.html.erb
<h1>New lesson_learned</h1>

<%= render 'form' %>

<%= link_to 'Back', lesson_learneds_path %> |
<%= link_to 'Home', root_path %>

app/views/lesson_learneds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Lesson Date:</b>
  <%= @lesson_learned.lessonDate %>
</p>

<p>
  <b>Project Reference:</b>
  <%= @lesson_learned.projectReference %>
</p>

<p>
  <b>Project Engineer:</b>
  <%= @lesson_learned.projectEngineer %>
</p>

<p>
  <b>Project Architect:</b>
  <%= @lesson_learned.projectArchitect %>
</p>

<p>
  <b>Project Owner:</b>
  <%= @lesson_learned.projectOwner %>
</p>

<p>
  <b>Division:</b>
  <%= @lesson_learned.division %>
</p>

<p>
  <b>Input:</b>
  <pre><%= @lesson_learned.input %></pre>
</p>


<%= link_to 'Edit', edit_lesson_learned_path(@lesson_learned) %> |
<%= link_to 'Back', lesson_learneds_path %> |
<%= link_to 'Home', root_path %>

app/views/lessons_learned_search/index.html.erb
<h1>Search Results</h1>

<table>
    <tr>
        <th>Lesson Date</th>
        <th>Project Reference</th>
        <th>Project Engineer</th>
        <th>Project Architect</th>
        <th>Project Owner</th>
        <th>Division</th>
        <th>Input</th>
        <th></th>
    </tr>

    <% @lessons_learned_search['response']['docs'].each do |lesson_learned| %>
        <tr>
            <td><%= lesson_learned['lesson_date'][0..9] %></td>
            <td><%= lesson_learned['project_reference'] %></td>
            <td><%= lesson_learned['project_engineer'] %></td>
            <td><%= lesson_learned['project_architect'] %></td>
            <td><%= lesson_learned['project_owner'] %></td>
            <td><%= lesson_learned['division'] %></td>
            <td><%= @lessons_learned_search['highlighting'][lesson_learned['id']]['text'][0].html_safe %></td>
            <td><a href="/lesson_learneds/<%= lesson_learned['id']%>">Show</a></td>
        </tr>
    <% end %>
</table>

<br/>

<%= link_to 'Home', root_path %>